// TWO DATATYPES ARE SHOWN HERE PRIMTIVE 
// AND 
// NON-PRIMITIVE/REFERENCE DATATYPES

//  1)PRIMITIVE DATATYPES
//  7 PRIMITIVE DATATYPES ARE THERE: STRING, NUMBER,
//  BOOLEAN, NULL, UNDEFINED, SYMBOL, BIGINT


// 2)NON-PRIMITIVE/REFERENCE DATATYPES
// 3 NON-PRIMITIVE DATATYPES ARE THERE: OBJECT, ARRAY, FUNCTION

// 1)OBJECT
// OBJECT IS COLLECTION OF KEY-VALUE PAIRS
// OBJECT IS USED TO STORE MULTIPLE VALUES
const person={
    name:'john',
    age:34
}


// 2)ARRAY
// ARRAY IS COLLECTION OF VALUES
// ARRAY IS USED TO STORE MULTIPLE VALUES
const heroes=['superman','batman','spiderman']


// 3)FUNCTION
// FUNCTION IS A BLOCK OF CODE THAT CAN BE REUSED
// FUNCTION IS USED TO PERFORM A SPECIFIC TASK
// FUNCTION IS USED TO PERFORM A SPECIFIC TASK
function greet(){
    console.log('hello world')
}
greet()

// 4)SYMBOL
// SYMBOL IS USED TO CREATE UNIQUE VALUES
// SYMBOL IS USED TO CREATE UNIQUE VALUES
const id1=Symbol('123')
const anotherId=Symbol('123')
console.log(id1===anotherId) //output is false;

// 5)BIGINT
// BIGINT IS USED TO STORE LARGE NUM
const bigNumber=234567890912234123345678909876543234n
console.log(bigNumber)








